mybatis:
  mapper-locations: classpath*:sqlmap/*.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sib?useAffectedRows=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: hyh
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 100
    initialSize: 10
    maxWait: 60000
    minIdle: 5
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT '1'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  servlet:
    multipart:
      max-file-size: 1500Mb
      max-request-size: 1500Mb

server:
  #端口号
  port: 8080
  servlet:
    contextPath: /sib

logging:
  config: classpath:logback-dev.xml